[package]
name = "can-bittiming-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.50", features = ["cargo", "derive"]}
serde = {version = "1.0.228", features = ["derive"]}
serde_json = "1.0.145"
